{% set version = "0.13.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-npflow
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/NPflow_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/NPflow/NPflow_{{ version }}.tar.gz
  sha256: a260594d5e8924c8d98c02a6a96d251e298954816cbbdc7776454879b7bb2592

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggally
    - r-rcpp >=0.12.11
    - r-rcpparmadillo
    - r-ellipse
    - r-fastcluster
    - r-ggplot2
    - r-pheatmap
    - r-reshape2
    - r-truncnorm
    - libblas
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-ggally
    - r-rcpp >=0.12.11
    - r-rcpparmadillo
    - r-ellipse
    - r-fastcluster
    - r-ggplot2
    - r-pheatmap
    - r-reshape2
    - r-truncnorm
  
  host:
    - r-base
    - r-rcpp >=0.12.11
    - r-rcpparmadillo
    - r-ellipse
    - r-fastcluster
    - r-ggplot2
    - r-pheatmap
    - r-reshape2
    - r-truncnorm

test:
  commands:
    - $R -e "library('NPflow')"           # [not win]
    - "\"%R%\" -e \"library('NPflow')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=NPflow
  license: LGPL-3.0-only
  summary: 'Dirichlet process mixture of multivariate normal, skew normal or skew t-distributions modeling oriented towards flow-cytometry data preprocessing applications. Method is detailed in: Hejblum, Alkhassimn, Gottardo, Caron & Thiebaut (2019) <doi: 10.1214/18-AOAS1209>.'
  license_family: LGPL
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - khusmann

# Package: NPflow
# Type: Package
# Title: Bayesian Nonparametrics for Automatic Gating of Flow-Cytometry Data
# Version: 0.13.3
# Date: 2020-02-06
# Authors@R: c(person(c("Boris", "P"), "Hejblum", role = c("aut", "cre"), email = "boris.hejblum@u-bordeaux.fr"), person("Chariff", "Alkhassim", role = c("aut"), email = "chariff.alkhassim@u-bordeaux.fr"), person("Francois", "Caron", role = c("aut"), email = "francois.caron@stats.ox.ac.uk") )
# LinkingTo: Rcpp, RcppArmadillo
# Depends: R (>= 3.1), Rcpp (>= 0.12.11), truncnorm
# Imports: graphics, stats, grDevices, ellipse, fastcluster, ggplot2, pheatmap, reshape2
# Suggests: foreach, parallel, doParallel, itertools, microbenchmark
# Description: Dirichlet process mixture of multivariate normal, skew normal or skew t-distributions modeling oriented towards flow-cytometry data preprocessing applications. Method is detailed in: Hejblum, Alkhassimn, Gottardo, Caron & Thiebaut (2019) <doi: 10.1214/18-AOAS1209>.
# License: LGPL-3 | file LICENSE
# BugReports: https://github.com/borishejblum/NPflow/issues
# Encoding: UTF-8
# RoxygenNote: 7.0.2
# NeedsCompilation: yes
# Packaged: 2020-02-06 12:02:56 UTC; boris
# Author: Boris P Hejblum [aut, cre], Chariff Alkhassim [aut], Francois Caron [aut]
# Maintainer: Boris P Hejblum <boris.hejblum@u-bordeaux.fr>
# Repository: CRAN
# Date/Publication: 2020-02-06 13:00:02 UTC
